name: vacatiion
description: A new Flutter project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+3

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.3+6  # CheckInternet
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.3+2
  toast: ^0.1.3
  http: ^0.12.0+2
  image_picker: ^0.6.0+16 #image_picker
  image_cropper: ^1.1.0 #image_cropper
 # flutter_image_compress: ^0.6.3 #Compress Image
  carousel_slider: ^1.3.0
  flutter_swiper: ^1.1.6 #Slider
  flutter_statusbarcolor: any # change statusbar's
  #pin_code_text_field: ^1.3.7
  smooth_star_rating: ^1.0.3
  spinner_input: ^0.1.2 #
  bubble_tab_indicator: ^0.1.4
  expandable: ^3.0.0+1
  rflutter_alert: ^1.0.3 # AlertDialog
  loading: ^1.0.1 # loading
  flutter_verification_code_input:
    git:
      url: git://github.com/tinylife-io/flutter_verification_code_input.git
  firebase_messaging: 5.1.5
  circular_profile_avatar: ^1.0.2
  flutter_spinkit: ^4.0.0
  get_it: ^3.0.0+1
  multi_image_picker: ^4.5.5
  geocoder: ^0.2.1 #----------Set lat,lng and Return names for location
  geolocator: ^5.1.3 #----GET Current location
  flutter_datetime_picker: ^1.2.6
  flutter_credit_card: ^0.1.3
  countdown: ^0.1.0
  flutter_range_slider: ^1.4.0
 # floating_search_bar: ^0.2.0
  device_info: ^0.4.0+2
 # map_view: ^0.0.14
  google_maps_flutter: ^0.5.21+7
  dio: any
  progress_dialog: ^1.2.0
  share: ^0.5.2
  access_settings_menu: ^0.0.1
  dashed_container: ^1.0.1
  flutter_launcher_icons: ^0.7.3
  photo_view: ^0.7.0
  mailer: ^3.0.4
  # meterial_design_icons_flutter: ^3.4.4595
  font_awesome_flutter: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
   android: true
   ios: true
   image_path: "assets/layer.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: DinNextLight
      fonts:
        - asset: fonts/DinNextLight.ttf
    - family: DinNextMedium
      fonts:
        - asset: fonts/DinNextMedium.ttf
    - family: DinNextRegular
      fonts:
        - asset: fonts/DinNextRegular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/splash/splashv.png
    - assets/splash/1.5x/splashv.png
    - assets/splash/2.0x/splashv.png
    - assets/splash/3.0x/splashv.png
    - assets/splash/4.0x/splashv.png
    - assets/icons/
    - assets/icons/1.5x/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/icons/4.0x/
    - assets/imagetest/
    - assets/background/
    - assets/background/1.5x/
    - assets/background/2.0x/
    - assets/background/3.0x/
    - assets/background/4.0x/
    - assets/appbar/
    - assets/appbar/1.5x/
    - assets/appbar/2.0x/
    - assets/appbar/3.0x/
    - assets/appbar/4.0x/
    - assets/bootom_navigation/
    - assets/bootom_navigation/1.5x/
    - assets/bootom_navigation/2.0x/
    - assets/bootom_navigation/3.0x/
    - assets/bootom_navigation/4.0x/
    - assets/button_click/
    - assets/button_click/1.5x/
    - assets/button_click/2.0x/
    - assets/button_click/3.0x/
    - assets/button_click/4.0x/
    - assets/logo/
    - assets/logo/1.5x/
    - assets/logo/2.0x/
    - assets/logo/3.0x/
    - assets/logo/4.0x/
    - assets/Views/
    - assets/Views/1.5x/
    - assets/Views/2.0x/
    - assets/Views/3.0x/
    - assets/logo/4.0x/
    - assets/
#    - assets/chalet.png




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
